-- 사용자 테이블
CREATE TABLE user (
    userId VARCHAR(100) PRIMARY KEY,        
    userName VARCHAR(100) NOT NULL,       
    userPw VARCHAR(255) NOT NULL,         
    createdTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,     
    lastModifiedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 게시글 테이블
-- CONTENT_BLOCK과 합침
CREATE TABLE post ( 
    postId INT AUTO_INCREMENT PRIMARY KEY,  
    userId VARCHAR(100) NOT NULL,                    
    postTitle VARCHAR(255) NOT NULL,        
    postContent TEXT NOT NULL,
    sFilename VARCHAR(255),
    oFilename VARCHAR(255),
    createdTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,        
    lastModifiedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES user(userId) ON DELETE CASCADE   
);

CREATE TABLE comment (
  comment_id INT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(100) NOT NULL,
  post_id INT NOT NULL,
  content_text VARCHAR(255) NOT NULL,
  createdTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,        
  lastModifiedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(userId) ON DELETE CASCADE,  
  FOREIGN KEY (post_id) REFERENCES post(postId) ON DELETE CASCADE
);



